#Spawnpoint for the /spawn command
spawn:
  x: 
  y:
  z:
  world:

#Spawnpoint for new players
newbiespawn:
  x:
  y:
  z:
  world:
  
#Default value, can be changed per user
max_num_of_homes: 3

#If a user reaches their warning-level-limit, they'll be banned automatically. You can specify the level of a warning when you issue i, and the levels from all of a user's warnings will be added together. Set to 0 if you want to disable this
warning_level_limit: 4

#Logs every single command (by all plugins) to the console, even if used the wrong way or will be cancelled
command_logger: true

#These commands are allowed while a player is in jail (of course, only if they have the permission)
allowed_commands_in_jail:
  - login
  - afk

#Color of a group/player in the tablist. First, the color from a chatplugin is used. If the groups color is set here it overwrites that and player-colors overwrite group-colors. If nothing is set white is used
colors:
  groups:
    Player: WHITE
    Trialmod: GREEN
    Mod: DARK_GREEN
    Admin: RED
  
  players:


new_user:
  #{username} will be replaced with the players name
  welcome_message: "Welcome {username} to the Server"
  message_color: "GREEN"
  username_color: "YELLOW"